const DEFAULT_POKEMON_GENERATION = 'generation-i'
const DEFAULT_POKEMON_FILTER_TYPE = 'all'
const DEFAULT_LANGUAGE = 'fr'
const DEFAULT_POKEMONS_COLUMNS = 2
const FETCH_ALL_GENERATIONS_KEY = 'fetch-all-generations'


const API_ENDPOINT = process.env.API_ENDPOINT || 'http://192.168.1.42:4000'

export {
    API_ENDPOINT,
    DEFAULT_POKEMONS_COLUMNS,
    DEFAULT_LANGUAGE,
    DEFAULT_POKEMON_FILTER_TYPE,
    DEFAULT_POKEMON_GENERATION,
    FETCH_ALL_GENERATIONS_KEY
}
