const DEFAULT_POKEMON_GENERATION = 'generation-i'
const DEFAULT_POKEMON_FILTER_TYPE = 'all'
const DEFAULT_LANGUAGE = 'fr'
const DEFAULT_POKEMONS_COLUMNS = 2
const FETCH_ALL_GENERATIONS_KEY = 'fetch-all-generations'

export {
    DEFAULT_POKEMONS_COLUMNS,
    DEFAULT_LANGUAGE,
    DEFAULT_POKEMON_FILTER_TYPE,
    DEFAULT_POKEMON_GENERATION,
    FETCH_ALL_GENERATIONS_KEY
}
