/* POKEMONS GENERATIONS */
export const SET_GENERATIONS = 'SET_GENERATIONS'

/* POKEMONS BY GENERATIONS */
export const SET_POKEMON_BY_GENERATIONS = 'SET_POKEMON_BY_GENERATIONS'

/* POKEMONS TYPES */
export const SET_POKEMON_TYPES = 'SET_POKEMON_TYPES'

/* APPLICATION OPTIONS */
export const SET_FILTER_POKEMON_TYPES = 'SET_FILTER_POKEMON_TYPES'
export const SET_FILTER_POKEMON_GENERATION = 'SET_FILTER_POKEMON_GENERATION'

