/* POKEMONS GENERATIONS */
export const SET_GENERATIONS = 'SET_GENERATIONS'

/* POKEMONS BY GENERATIONS */
export const SET_POKEMON_BY_GENERATIONS = 'SET_POKEMON_BY_GENERATIONS'
export const SET_SELECTED_POKEMON = 'SET_SELECTED_POKEMON'

/* POKEMONS TYPES */
export const SET_POKEMON_TYPES = 'SET_POKEMON_TYPES'
export const SET_POKEMON_NAMES = 'SET_POKEMON_NAMES'
export const SET_LOADING_PROGRESS = 'SET_LOADING_PROGRESS'

/* APPLICATION OPTIONS */
export const SET_FILTER_POKEMON_TYPES = 'SET_FILTER_POKEMON_TYPES'
export const SET_FILTER_POKEMON_GENERATION = 'SET_FILTER_POKEMON_GENERATION'

